---
apiVersion: v1
kind: Namespace

metadata:
    name: myns
    labels:
        version: v1

---
apiVersion: v1
kind: Pod

metadata:
   name: fortune-pod
   namespace: myns
   labels:
     name: fortune
     version: v1

spec:
    containers:
    - name: fortune-container
      image: wan2019/myfortuneapp:latest
      imagePullPolicy: Always
      env:
      - name: APP_PORT
        value: "3000"
      ports:
      - name: http
        containerPort: 3000
