---
apiVersion: v1
kind: Namespace

metadata:
   name: nwdb
   labels:
      version: v1

---
apiVersion: v1
kind: Secret

metadata:
   name: nwdb-secret
   namespace: nwdb

data:
   # hellowworld
   db_password: aGVsbG93d29ybGQ=

---
apiVersion: v1
kind: ConfigMap

metadata:
   name: nwdb-config
   namespace: nwdb

data:
   db_user: root
   db_host: nwdb-svc.nwdb.svc.cluster.local

---
apiVersion: apps/v1
kind: Deployment

metadata:
   name: nwdb-deploy
   namespace: nwdb
   labels:
      name: nwdb
      version: v1
spec:
   replicas: 1
   minReadySeconds: 60
   selector:
      matchLabels:
         name: nwdb
         version: v1
   template:
      # pod template
      metadata:
         name: nwdb-pod
         labels:
            name: nwdb
            version: v1
      spec:  
         containers:
         - name: nwdb-container
           image: wan2019/northwinddb:v2
           imagePullPolicy: IfNotPresent
           env:
           - name: MYSQL_ROOT_PASSWORD
             valueFrom:
                secretKeyRef:
                   name: nwdb-secret
                   key: db_password
           ports:
           - name: mysql-port
             containerPort: 3306

---
apiVersion: v1
kind: Service

metadata:
   name: nwdb-svc
   namespace: nwdb
   labels:
      name: nwdb-svc
      version: v1

spec:
   type: ClusterIP
   selector:
      name: nwdb
      version: v1
   ports:
   - name: db-port
     port: 3306
     targetPort: mysql-port


---
apiVersion: apps/v1
kind: Deployment

metadata:
   name: nwapp-deploy
   namespace: nwdb
   labels:
      name: nwapp
      version: v1
spec:
   replicas: 3
   minReadySeconds: 60
   selector:
      matchLabels:
         name: nwapp
         version: v1
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 1
         maxUnavailable: 1
   template:
      # pod template
      metadata:
         name: nwapp-pod
         labels:
            name: nwapp
            version: v1
      spec:  
         containers:
         - name: nwapp-container
           image: stackupiss/northwind-app:v2
           imagePullPolicy: IfNotPresent
           env:
           - name: DB_PASSWORD
             valueFrom:
                secretKeyRef:
                   name: nwdb-secret
                   key: db_password
           - name: DB_HOST
             valueFrom:
                configMapKeyRef:
                   name: nwdb-config
                   key: db_host
           - name: DB_USER
             valueFrom:
                configMapKeyRef:
                   name: nwdb-config
                   key: db_user
           - name: INSTANCE_IP_ADDRESS
             valueFrom:
                fieldRef:
                   fieldPath: status.hostIP
           ports:
           - name: nwapp-port
             containerPort: 3000

---
apiVersion: v1
kind: Service

metadata:
   name: nwapp-svc
   namespace: nwdb
   labels:
      name: nwapp-svc
      version: v1

spec:
   type: LoadBalancer
   selector:
      name: nwapp
      version: v1
   ports:
   - name: app-port
     port: 80
     targetPort: nwapp-port

