version: '3'

networks:
   appnet:

volumes:
   appvol:

services:
   nwdb:
    image: wan2019/northwindb:latest
    build:
      context: ./database
    environment:
     - MYSQL_ROOT_PASSWORD=changeit
    networks:
     - appnet
    volumes:
     - appvol:/var/lib/mysql
     
   nwapp:
    image: wan2019/nwapp:latest
    build:
       context: ./server
    networks:
     - appnet
    environment:
     - DB_HOST=nwdb
    ports:
     - 80:3000
